/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  docs:[
    'intro',
    {
      type: 'category',
      label: 'Idea',
      collapsed: false,
      items: [
        'idea/congratulations',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: [
        'tutorial/manage-docs-versions',
        'tutorial/translate-your-site',
      ],
    },
  ],
  app:[
    'privacy',
    {
      type: 'category',
      label: 'Mobile',
      collapsed: false,
      items: [
        'app/mobile/mobile',
      ],
    },
    {
      type: 'category',
      label: 'Web',
      collapsed: false,
      items: [
        'app/web/web',
      ],
    },
    {
      type: 'category',
      label: 'Unity',
      collapsed: false,
      items: [
        'app/unity/unity',
      ],
    },
    {
      type: 'category',
      label: 'Problem',
      collapsed: false,
      items: [
        'app/problem/problem1',
      ],
    },
  ]
  */
};
